import type {CustomPlugin} from "svgo";
import colors from "@sproutsocial/seeds-color";

type CustomPluginWithDescription = CustomPlugin & { description: string }

// Designers usually add fills to the icons in Figma, usually a neutral color by default.
// For those "default fills", we want to strip them out of the resulting icon entirely.
// If the color isn't neutral, we assume this icon is a special, pre-colored icon, so we don't strip out the fill.
const obj: { [index: string]: any } = {}
const neutralColorObjects = Object.keys(colors)
    .filter((colorName) => colorName.includes('NEUTRAL') && colorName !== 'COLOR_NEUTRAL_0')
    .reduce((obj, key) => {
        obj[key] = colors[key];
        return obj;
    }, obj);

const neutralColors = ['#FFF', ...Object.values(neutralColorObjects)];

const plugin: CustomPluginWithDescription = {
    name: 'removeNeutralFills',
    description: 'Remove unnecessary neutral fills generated by Figma',
    fn: (_root) => {
        return {
            element: {
                enter: (node) => {
                    if (neutralColors.includes(node?.attributes?.fill)) {
                            node.attributes.fill = "currentColor";
                    }
                }
            }
        }
    }
}

export default plugin;